# Generated by Django 2.1 on 2018-08-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180821_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
    ]
