# Generated by Django 2.1 on 2018-08-22 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_remove_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'INACTIVE'), ('A', 'ACTIVE')], default='A', max_length=50),
        ),
    ]
