# Generated by Django 2.1 on 2018-08-22 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180822_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
