# Generated by Django 2.1 on 2018-08-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20180824_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'INACTIVE'), ('A', 'ACTIVE')], default='A', max_length=50),
        ),
    ]
