# Generated by Django 2.1 on 2018-08-27 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20180824_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ratings',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('D', 'INACTIVE')], default='A', max_length=50),
        ),
    ]
