# Generated by Django 2.1 on 2018-08-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20180827_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ratings',
            field=models.IntegerField(verbose_name=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'INACTIVE'), ('A', 'ACTIVE')], default='A', max_length=50),
        ),
    ]
