# Generated by Django 2.1 on 2018-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20180827_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('D', 'INACTIVE')], default='A', max_length=50),
        ),
    ]
