# Generated by Django 2.1 on 2018-08-28 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20180828_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ratings',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'INACTIVE'), ('A', 'ACTIVE')], default='A', max_length=50),
        ),
    ]
