# Generated by Django 2.1 on 2018-08-29 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20180829_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ratings',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
