# Generated by Django 2.1 on 2018-08-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20180829_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('D', 'INACTIVE')], default='A', max_length=50),
        ),
    ]
